name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Install gulp
        run: npm install --global gulp-cli
      - name: Build
        run: |
          yarn
          yarn build
        env: 
          CI: ""
      - name: Tar it
        run: tar -cvC ./build . >instaswarm.tar
      - name: Upload to Gateway
        run: `curl -X POST -H "Content-Type: application/x-tar" -H "Swarm-Index-Document: index.html" -H "Swarm-Error-Document: index.html" --data-binary @../instaswarm.tar https://bee-gateway.duckdns.org/dirs`
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
     