- name: Github Build & Deploy Action
  uses: jeoy/github-deploy-actions@v1.0.1

name: deploy

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Build and Deploy
              uses: ./.github/actions/deploy
              env:
                  COMMIT_EMAIL: michelle@ethswarm.org
                  COMMIT_NAME: Michelle
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BASE_BRANCH: master
                  DEPLOY_BRANCH: gh-pages
                  BUILD_SCRIPT: yarn && yarn build
                  FOLDER: build
