name: github pages

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Install gulp
        run: npm install --global gulp-cli
      - name: Build
        run: |
          yarn
          yarn build
        env: 
          CI: ""
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
     