name: 'build-test'
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_BEE_API: https://api.gateway.ethswarm.org
      REACT_APP_BEE_DEBUG_API: https://api.gateway.ethswarm.org
      REACT_APP_BEE_GATEWAY_MODE: true
      DISABLE_ESLINT_PLUGIN: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Build
        run: |
          yarn
          yarn build

      - uses: ethersphere/swarm-actions/upload-dir@v0
        id: upload
        with:
          dir: ./build
          index-document: index.html
          postage-batch-id: ${{ secrets.POSTAGE_BATCH_ID }}
          bee-url: ${{ secrets.BEE_URL }}
          timeout: 3000000
          headers: |
            authorization: ${{ secrets.API_TOKEN }}

      - uses: ethersphere/swarm-actions/write-feed@v0
        id: feed
        with:
          reference: ${{ steps.upload.outputs.reference }}
          topic: 'kurate'
          postage-batch-id: ${{ secrets.POSTAGE_BATCH_ID }}
          bee-url: ${{ secrets.BEE_URL }}
          signer: ${{ secrets.SIGNER }}
          headers: |
            authorization: ${{ secrets.API_TOKEN }}

      - uses: ethersphere/swarm-actions/reference-to-cid@v0
        id: cid
        with:
          reference: ${{ steps.feed.outputs.manifest }}

      - run: |
          echo 'Chunk Reference: ${{ steps.upload.outputs.reference }}'
          echo 'Feed Reference: ${{ steps.feed.outputs.reference }}'
          echo 'Feed Manifest: ${{ steps.feed.outputs.manifest }}'
          echo 'Feed Bzz.link: https://${{ steps.cid.outputs.cid }}.bzz.link'
