name: 'build-test'
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GENERATE_SOURCEMAP: false
      REACT_APP_BEE_GATEWAY: https://bee-api.duckdns.org/
      REACT_APP_WEB3_GATEWAY: https://dai.poa.network/
      REACT_APP_API_TOKEN: 32a5c36a794e22de2b5538c5bcb6ab8a4a95d823e381b90789cdceb3348ff1678446d12f74df338d4058621aa44a91b4278a
      REACT_APP_USER_REGISTRY_ADDRESS: 0x
      REACT_APP_KURA_NFT_ADDRESS: 0x
      REACT_APP_VERSION: 0.1.0
      REACT_APP_POSTAGE_BATCH_ID: 4963fa02eb78dc4cd22008df7e326095bffc23e4be90be360a61aec9a1c100ca
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Build
        run: |
          yarn
          yarn build

      - uses: ethersphere/swarm-actions/upload-dir@v0
        id: upload
        with:
          dir: ./build
          index-document: index.html
          postage-batch-id: ${{ secrets.POSTAGE_BATCH_ID }}
          bee-url: ${{ secrets.BEE_URL }}
          timeout: 3000000
          headers: |
            authorization: ${{ secrets.API_TOKEN }}

      - uses: ethersphere/swarm-actions/write-feed@v0
        id: feed
        with:
          reference: ${{ steps.upload.outputs.reference }}
          topic: 'kurate'
          postage-batch-id: ${{ secrets.POSTAGE_BATCH_ID }}
          bee-url: ${{ secrets.BEE_URL }}
          signer: ${{ secrets.SIGNER }}
          headers: |
            authorization: ${{ secrets.API_TOKEN }}

      - uses: ethersphere/swarm-actions/reference-to-cid@v0
        id: cid
        with:
          reference: ${{ steps.feed.outputs.manifest }}

      - run: |
          echo 'Chunk Reference: ${{ steps.upload.outputs.reference }}'
          echo 'Feed Reference: ${{ steps.feed.outputs.reference }}'
          echo 'Feed Manifest: ${{ steps.feed.outputs.manifest }}'
          echo 'Feed Bzz.link: https://${{ steps.cid.outputs.cid }}.bzz.link'
