name: PR Preview

on:
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      REACT_APP_BEE_GATEWAY: https://bee-api.duckdns.org/
      REACT_APP_WEB3_GATEWAY: https://dai.poa.network/
      REACT_APP_API_TOKEN: 32a5c36a794e22de2b5538c5bcb6ab8a4a95d823e381b90789cdceb3348ff1678446d12f74df338d4058621aa44a91b4278a
      REACT_APP_USER_REGISTRY_ADDRESS: 0x
      REACT_APP_KURA_NFT_ADDRESS: 0x
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      ## Try getting the node modules from cache, if failed npm ci
      - uses: actions/cache@v2
        id: cache-npm
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-${{ matrix.node-version }}-${{ env.cache-name }}-
            ${{ runner.OS }}-node-${{ matrix.node-version }}-

      - name: Install npm deps
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create preview
        uses: ethersphere/swarm-actions/pr-preview@v0
        with:
          dir: ./build
